# version: "3.9"

# services:
#   job-service:
#     build: ./job-service
#     command: go run ./cmd
#     volumes:
#       - ./job-service:/app
#     working_dir: /app

#   api-service:
#     build: ./api-service
#     command: go run ./cmd
#     volumes:
#       - ./api-service:/app
#     working_dir: /app
#     ports:
#       - "8080:8080"

version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: sp500_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: sp500_shariah
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
