version: "3.9"

services:
  job-service:
    build: ./job-service
    command: go run ./cmd
    volumes:
      - ./job-service:/app
    working_dir: /app

  api-service:
    build: ./api-service
    command: go run ./cmd
    volumes:
      - ./api-service:/app
    working_dir: /app
    ports:
      - "8080:8080"
